theme = "gruvbox"

[editor]
scrolloff = 5
line-number = "relative"
cursorline = true
rulers = [72, 103]
color-modes = true
bufferline = "multiple"
auto-save = true
idle-timeout = 0
mouse = false

[editor.statusline]
left = ["mode", "file-name", "spinner"]
right = ["diagnostics", "selections", "position", "position-percentage", "version-control", "file-encoding", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[keys.normal]
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]

[keys.select]
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

