
[[language]]
name = "c"
auto-format = true
language-servers = ["clangd" ]
formatter = { command = "clang-format", args=["--style={BasedOnStyle: GNU, IndentWidth: 2}"]}

[[language]]
name = "go"
auto-format = true
# language-servers = ["gopls" ]
formatter = { command = "gofmt"}

[[language]]
name = "tiger"
scope = "source.tig"
file-types = ["tig"]
roots = []
auto-format = true

[[grammar]]
name = "tiger"
source = { git = "https://github.com/ambroisie/tree-sitter-tiger.git", rev =  "main"}


[[language]]
name = "typst"
auto-format = true
scope = "source.typst"
injection-regex = "typst"
file-types = ["typst", "typ"]
comment-token = "//"
language-servers = ["typst-lsp"]
indent = { tab-width = 2, unit = "  " }
roots = []


[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'$' = '$'
'"' = '"'

[[grammar]]
name = "typst"
source = { git = "https://github.com/uben0/tree-sitter-typst", rev = "master" }

[[language]]
name = "gnuplot"
scope = "source.gp"
file-types = ["gp"]
roots = []
auto-format = true

[[grammar]]
name = "gnuplot"
source = { git = "https://github.com/dpezto/tree-sitter-gnuplot", rev = "release" }
