[theme]
theme = "native"
[icons]
icons = "awesome6"

[[block]]
block = "custom"
command =''' /./home/rodolphe/.config/i3status-rust/modules/fan.sh''' 
interval = 1

[[block]]
block = "time"
interval = 5
[block.format]
full = "$icon $timestamp.datetime(f:'%a %d/%m %R', l:fr_BE)"

[[block]]
block = "memory"
format = "$mem_used.eng(w:1)/$mem_total "
format_alt = " $icon_swap $swap_free.eng(w:3,u:B,p:M)/$swap_total.eng(w:3,u:B,p:M)($swap_used_percents.eng(w:2)) "
interval = 1
warning_mem = 80
critical_mem = 95

[[block]]
block = "cpu"
format = "$barchart $utilization "
interval = 1

[[block]]
block = "custom"
command =''' /./home/rodolphe/.config/i3status-rust/modules/temp.sh''' 
interval = 1

[[block]]
block = "sound"
format = " $icon {$volume|} "
[block.mappings]
"alsa_output.usb-Harman_Multimedia_JBL_Pebbles_1.0.0-00.analog-stereo" = "🔈"
"alsa_output.pci-0000_00_1b.0.analog-stereo" = "🎧"

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT0"

[[block]]
block = "net"
format = " $icon {$ip}"
